### PR TITLE
Massively reimplement applyColorSchemeJs

### LINKED ISSUE #30: Automatic theme change not working in Open Fixture Library
**Affected website:** Open Fixture Library (https://open-fixture-library.org/). *Disclosure: I'm the author of that page :wink:*

## Bug description

The theme is not automatically toggled when clicking the extension's button. The correct theme is applied after a page reload.

## Steps to reproduce

1. Go to https://open-fixture-library.org/
2. Click the extension's button to toggle the theme

### Actual behavior

The page theme does not change immediately.

### Expected behavior

The page theme should change.

## System

Operating system and version: Ubuntu 20.04
Browser and version: Firefox 84.0
Add-on version: 1.2

## Possible solution

The page's theme switcher code is located here: https://github.com/OpenLightingProject/open-fixture-library/blob/master/ui/components/ThemeSwitcher.vue

We use `mediaQuery.addListener` to listen for changes (and toggle an attribute on the `<html>` element), but that listener is never called.

### PR DESCRIPTION
**Pull request by tartpvule**
A redesign of applyColorSchemeJs

Hijack prototypes instead of overwriting matchMedia.
"matches" getter on MediaQueryList.
Dispatch events. Fixes #30
Track, hook and disguise "change" event listeners.
Tries to be as defensive as possible.

Highly dependent on Firefox's implementation of content scripts.

### CODE REVIEW

File: src/content_scripts/applyColorSchemeJs.js [hunk 1]
```diff
@@ -38,95 +68,240 @@ function getColorTypeFromMediaQuery(mediaQueryString) {
...
+        mediaQueryList.dispatchEvent(event);
     }
+    dispatching = false;
 
-    // pass to default function, by default
-    return window.matchMedia(...args);
+    jsColorStatus = fakedColorStatus;
 }
 
+
```
Comment (rugk) [inline src/content_scripts/applyColorSchemeJs.js:304]: superfluous empty line

File: src/content_scripts/common.js [hunk 2]
```diff
@@ -8,6 +8,9 @@
 let functionalMode = null;
 let fakedColorStatus = null;
 
+// the color status last shown to the page javascript
+let jsColorStatus = fakedColorStatus;
```
Comment (rugk) [inline src/content_scripts/common.js:12]: Hmm? Why do you need to save it two times? Is not `fakedColorStatus` enough?

File: src/content_scripts/applyColorSchemeJs.js [hunk 3]
```diff
@@ -136,15 +311,54 @@ function matchMediaOverwrite(...args) {
...
+        value: exportFunction(skeleton.addListener, window),
+        writable: true
+    });
+    Reflect.defineProperty(MediaQueryListPrototype, 'removeListener', {
+        configurable: true,
+        enumerable: true,
+        value: exportFunction(skeleton.removeListener, window),
+        writable: true
+    });
+    let descMatches = Reflect.getOwnPropertyDescriptor(skeleton, 'matches');
```
Comment (rugk) [inline src/content_scripts/applyColorSchemeJs.js:334]: Better use variable names without abbreviations to make it easier to understand/and less easier to mistake. I would translate `descMatches` as `descriptionMatches` e.g., but I doubt that is correct.

Same below.

**Comment by rugk** [comment]
Hi @tartpvule,
thanks for your first contribution to this project! :tada: :+1: 🏅
I hope you'll like this project and enjoy hacking on it… :smiley:

Thanks a lot for tackling this issue and fixing it! :smiley: 

BTW: Next time, try to avoid doing a pull request from the master branch, because you can run into problems when you have a "non-clean" master that does not follow this repo here (i.e. "upstream"). [See this article for details](https://help.github.com/en/articles/proposing-changes-to-your-work-with-pull-requests). Anyway, this is only a tip for the next time. :smiley:

I'll do a quick review…

**Review by rugk — CHANGES_REQUESTED** [review]
Thanks again for your work on all that!

First of all, could you please go through the test sites here, to check that they still work? https://github.com/rugk/website-dark-mode-switcher/wiki/Release-Test

I've added the on from #30 just now.

Also, could you please run EsLint over that code and fix all errors, according to our contribution guidelines: https://github.com/TinyWebEx/common/blob/master/CONTRIBUTING.md#js
I've tried it locally and found a lot of ones. There are many now unused variables etc.
I tried Eslint's auto-correction for the ones that can automatically be corrected, but unfortunately cannot push into your branch (there should be a checkbox at the right, where you can allow me to do this.)

File: src/content_scripts/applyColorSchemeJs.js [hunk 4]
```diff
@@ -38,95 +68,240 @@ function getColorTypeFromMediaQuery(mediaQueryString) {
...
+            typeof listener !== 'function' ||
+            evaluateMediaQuery(this.media) === null
+        ) {
+            return Reflect.apply(originalAddEventListener, this, arguments);
+        }
+        let hook = _OnListener(listener, this, false);
+        return Reflect.apply(originalAddEventListener, this, ['change', hook, options]);
+    },
+    removeEventListener(type, listener, options) {
+        if (Object.prototype.toString.call(this) !== '[object MediaQueryList]' ||
```
[the remark this answers is not in the document]
Comment (tartpvule) [reply src/content_scripts/applyColorSchemeJs.js:235]: Those are parameter/environment validations.
Should I move the whole `Object.prototype.toString.call(this) !== '[object MediaQueryList]'` out into a new function?
Or just the `Object.prototype.toString.call(this)` part?
In my opinion, keeping them like that actually helps making what is going on explicit.

File: src/content_scripts/common.js (hunk 2 above)
Comment (tartpvule) [reply src/content_scripts/common.js]: Oops, that is a leftover thing from earlier experiments.

File: src/content_scripts/applyColorSchemeJs.js (hunk 3 above)
Comment (tartpvule) [reply src/content_scripts/applyColorSchemeJs.js]: It's "descriptor".

**Comment by tartpvule** [comment]
```
First of all, could you please go through the test sites here, to check that they still work? https://github.com/rugk/website-dark-mode-switcher/wiki/Release-Test
```
Does not work on `https://duckduckgo.com/` and `https://pinafore.social/`, but from my tests, the current master and release also does not work. Specifically, step 3 failed.
From a cursory reading of the site's source code, I don't see any "change" event listeners, so I'm not sure that changing theme after the page is loaded is implemented at all by the site.


Some explanations about `no-setter-return` ESLint error in `set onchange`.
Changing it to `Reflect.apply(originalOnChangeSetter, this, arguments); return;` will work mostly the same, but I think it is prudent to make it clear that we are handing things over to another method (hook chaining).

**Comment by tartpvule** [comment]
> ... but unfortunately cannot push into your branch (there should be a checkbox at the right, where you can allow me to do this.)

Hmm, I have the `Allow edits by maintainers` checked. Should I look for something else?

File: src/content_scripts/applyColorSchemeJs.js [hunk 5]
```diff
@@ -194,7 +190,8 @@ const skeleton = {
         }
         let func = wmHookToFunc.get(hook);
         if (typeof func !== 'function') {
-            // !!! BAD GUY !!!
+            // ! someone called us on an unknown MediaQueryList
+            // ! may be a hacking attempt
```
Comment (rugk) [inline src/content_scripts/applyColorSchemeJs.js:194]: well… bold claim, and I also don't know what implications this would have (i.e. why would someone do this?).
But anyway, what do you think about logging an `console.error` here? If it is such an invalid operation, we may make this visible and not (only) silently ignore it.

File: src/content_scripts/applyColorSchemeJs.js [hunk 6]
```diff
@@ -6,8 +6,6 @@
 
 let overwroteMatchMedia = false;
 
-const ADDON_FAKED_WARNING = "matchMedia has been faked/overwritten by add-on website-dark-mode-switcher; see https://github.com/rugk/website-dark-mode-switcher/. If it causes any problems, please open an issue.";
```
Comment (rugk) [inline src/content_scripts/applyColorSchemeJs.js:9]: Well, don't just remove it.
IIRC it was there for logging this to the user-visible console, when the API was accessed.

Can't we still log that? It may be useful for debugging when users report issues with the dark theme for web developers, because they e.g. accidentally forget they had this add-on installed. :wink:

Or is this too hard to implement?

File: src/content_scripts/common.js [hunk 7]
```diff
@@ -3,14 +3,13 @@
 /* eslint-disable no-unused-vars */
 /* eslint-disable prefer-const */
 
+/* globals browser */
```
Comment (rugk) [inline src/content_scripts/common.js:6]: Usually our EsLint config file includes this already, i.e. it knows we are operating as a web extension.
As such, you should be able to remove this here.

**Review by rugk — CHANGES_REQUESTED** [review]

File: src/content_scripts/applyColorSchemeJs.js (hunk 4 above)
[the remark this answers is not in the document]
Comment (rugk) [reply src/content_scripts/applyColorSchemeJs.js:235]: Code-wise you just do the same on multiple lines here, so I'd argue you should try to refactor as much as possible into a reusable function.
If it does something different, then of course not, but I saw that at least the whole `if` condition is the same.
Then you'd also give that a readable name and it should be a lot cleaner/easier readable code.

The whole ECMASPec details are already a huge thing I don't get here, but it's fine if it's wrapped in some function.

**Comment by rugk** [comment]
Also note there were some requests to have this for Chrome/ium (https://github.com/rugk/website-dark-mode-switcher/issues/27), which this PR likely would make impossible.
Though I'm thinking of whether that would be useful. Maybe some day we'd need to reintroduce the old version (partially) as a fallback at least or so.

Just letting you (and my future-self) know that this really makes it Firefox-only, so one should be aware of that.

File: src/content_scripts/applyColorSchemeJs.js (hunk 5 above)
Comment (tartpvule) [reply src/content_scripts/applyColorSchemeJs.js]: With vanilla DOM, it is not an invalid operation, just very unusual.
Kind of like using another window's `alert` and `confirm` methods.
But in this case, we cannot keep track of things not from our window, so another window's `MediaQueryList`s hooks are going to be completely unknown to us.
Those checks are there to avoid wreaking havoc on our `setMediaQueryLists`, it could lead to memory leaks otherwise.

File: src/content_scripts/applyColorSchemeJs.js (hunk 6 above)
Comment (tartpvule) [reply src/content_scripts/applyColorSchemeJs.js:9]: OK, a message when the hooks are installed.

File: src/content_scripts/applyColorSchemeJs.js (hunk 4 above)
[the remark this answers is not in the document]
Comment (tartpvule) [reply src/content_scripts/applyColorSchemeJs.js]: OK

**Comment by tartpvule** [comment]
> Just letting you (and my future-self) know that this really makes it Firefox-only, so one should be aware of that.

It is possible to port this over to Chromium, but there is neither `XPCNativeWrapper` nor a separate execution context for content scripts there, so a separate set hooks will have to be developed for them.
The main ideas will be the same, but security properties and detectibility will be vastly inferior.

**Comment by tartpvule** [comment]
Hey, just to let you know, this fixes theme switching in Twitter, too.
https://twitter.com/rugkme
:smile:

**Comment by tartpvule** [comment]
@rugk Do not merge this yet, I forgot about `NO_OVERWRITE`, fixing it.
:cry:

File: src/content_scripts/applyColorSchemeJs.js [hunk 8]
```diff
@@ -144,9 +146,21 @@ function _OffListener(func, mediaQueryList, isOnChange) {
...
 
+/**
+ * Check if an object is a MediaQueryList
+ * The correctness of this relies on Firefox's XPCNativeWrapper
+ *
+ * @private
+ * @param {function} obj
+ * @returns {boolean}
+ */
+function _checkIsMediaQueryList(obj) {
```
Comment (rugk) [inline src/content_scripts/applyColorSchemeJs.js:157]: Please remove that `_` prefix from all functions, we don't use it here. It's enough to use use JSDoc to mark a function as `@private`.

File: src/content_scripts/applyColorSchemeJs.js [hunk 9]
```diff
@@ -355,6 +367,7 @@ function applyJsOverwrite() {
     });
 
     overwroteMatchMedia = true;
+    console.log(ADDON_FAKED_WARNING);
```
Comment (rugk) [inline src/content_scripts/applyColorSchemeJs.js:370]: As far as I see this logs a message on each site, basically, as the add-on modifies that everywhere.
Sorry, but this is not what I intended.

As you can see in https://github.com/rugk/website-dark-mode-switcher/issues/11, there was quite some discussion about too many logs by this add-on, so I've modified it to only log something _when the add-on actively does sth._, i.e. if “it fakes the result of a JS”.
So better only print that log when the website accesses the “faked” API.

**Review by rugk — CHANGES_REQUESTED** [review]

**Comment by rugk** [comment]
> https://twitter.com/rugkme

Hehe nice, thanks! Added [that to the test website list](https://github.com/rugk/website-dark-mode-switcher/wiki/Release-Test).

> There is a logic bug in getColorTypeFromMediaQuery.

Maybe due to the fact I have written the code, I see no bug in there. But… well free to explain/fix it. :thinking: 

Also note that practically the add-on also only toggles between `NO_OVERWRITE` and `LIGHT`.

**Comment by tartpvule** [comment]
> Maybe due to the fact I have written the code, I see no bug in there. But… well free to explain/fix it.

`(MEDIA_QUERY_PREFER_COLOR[COLOR_STATUS.NO_PREFERENCE])` is always true.

**Comment by tartpvule** [comment]
Fixes https://www.youtube.com/ too. :tada:

**Comment by tartpvule** [comment]
No bugs I can see now.
If you see anything else, please let me know.

File: src/content_scripts/common.js [hunk 10]
```diff
@@ -8,6 +8,9 @@
 let functionalMode = null;
 let fakedColorStatus = null;
 
+// last setting seen by js
+let jsLastColorStatus = null;
```
Comment (rugk) [inline src/content_scripts/common.js:12]: You still need to explain this. Is not this always the same as `fakedColorStatus`? Both are modified (only?) when a new setting is set by the add-on…

**Comment by rugk** [comment]
> (MEDIA_QUERY_PREFER_COLOR[COLOR_STATUS.NO_PREFERENCE]) is always true.

Oh thanks a lot! Of course! :sweat_smile:

File: src/content_scripts/applyColorSchemeJs.js [hunk 11]
```diff
@@ -22,109 +51,294 @@ const ADDON_FAKED_WARNING = "matchMedia has been faked/overwritten by add-on web
...
+    removeEventListener(type, listener, options) {
+        if (!checkIsMediaQueryList(this) ||
+            type !== 'change' ||
+            typeof listener !== 'function' ||
+            !hasColorMediaQuery(this.media)
+        ) {
+            return Reflect.apply(originalRemoveEventListener, this, arguments);
+        }
+        let hook = trackOffListener(listener, this, false);
+        if (!hook) {
```
Comment (rugk) [inline src/content_scripts/applyColorSchemeJs.js:274]: Wanna do a strict function type-check here, too?

File: src/content_scripts/applyColorSchemeJs.js [hunk 12]
```diff
@@ -22,109 +51,294 @@ const ADDON_FAKED_WARNING = "matchMedia has been faked/overwritten by add-on web
...
+ *
+ * @private
+ * @param {function} obj
+ * @returns {boolean}
+ */
+function checkIsMediaQueryList(obj) {
+    return (Object.prototype.toString.call(obj) === '[object MediaQueryList]');
+}
+
+const skeleton = {
```
Comment (rugk) [inline src/content_scripts/applyColorSchemeJs.js:178]: Could you add a `jsdoc` thing here to describe what the skelecton is?

https://jsdoc.app/tags-property.html

File: src/content_scripts/applyColorSchemeJs.js [hunk 13]
```diff
@@ -22,109 +51,294 @@ const ADDON_FAKED_WARNING = "matchMedia has been faked/overwritten by add-on web
...
-            // …because we only fake/create an object, not a real MediaQueryList
-        },
-        removeListener: (...args) => {
-            console.warn(ADDON_FAKED_WARNING);
+    let hook, setMediaQueryList, setMediaQueryListOnChange;
+    if (!entry) {
+        hook = makeListenerHook(func);
+        setMediaQueryList = new Set();
+        setMediaQueryListOnChange = new Set();
+        wmFuncToEntry.set(func, { hook, setMediaQueryList, setMediaQueryListOnChange });
```
Comment (rugk) [inline src/content_scripts/applyColorSchemeJs.js:119]: Hmm this Object deconstruction is AFAIK a newer JS feature than what the oldest Firefox version we support, supports.

See here for the minimal Firefox version that should be supported:
https://github.com/rugk/website-dark-mode-switcher/blob/7c311125b670ed603983f5b56cac26dae36edb6d/src/manifest.json#L76 

Note that we could discuss bumping this of course, if it is too hard to implement to a newer ESR version, at least. It should, at minimum, however, support the latest still stable ESR Firefox version.

File: src/content_scripts/applyColorSchemeJs.js [hunk 14]
```diff
@@ -22,109 +51,294 @@ const ADDON_FAKED_WARNING = "matchMedia has been faked/overwritten by add-on web
...
+ * Creates hook function if necessary
+ *
+ * @private
+ * @param {function} func original listener
+ * @param {MediaQueryList} mediaQueryList
+ * @param {boolean} isOnChange
+ * @returns {function} hook
+ */
+function trackOnListener(func, mediaQueryList, isOnChange) {
+    let entry = wmFuncToEntry.get(func);
```
Comment (rugk) [inline src/content_scripts/applyColorSchemeJs.js:112]: `wmFuncToEntry`  What? Is there any way to use a more descriptive (no abbreviations again) variable name? Clean coding and so on…

File: src/content_scripts/applyColorSchemeJs.js [hunk 15]
```diff
@@ -22,109 +51,294 @@ const ADDON_FAKED_WARNING = "matchMedia has been faked/overwritten by add-on web
...
+    return (fakedColorStatus === requestedMedia);
+}
 
-            return realQuery.addListener(...args);
+/**
+ * Keep track of listener addition
+ * Creates hook function if necessary
+ *
+ * @private
+ * @param {function} func original listener
```
Comment (rugk) [inline src/content_scripts/applyColorSchemeJs.js:106]:
```suggestion
 * @param {func} func original listener
```

The param name here diverges from the actual function declaration.

Though again these are abbreviations and I'd still avoid them. Or, e.g. name the actual type/thing what the function passed in here does. It certainly cannot be "any" function.

File: src/content_scripts/applyColorSchemeJs.js [hunk 16]
```diff
@@ -22,109 +51,294 @@ const ADDON_FAKED_WARNING = "matchMedia has been faked/overwritten by add-on web
...
-    if (fakedColorStatus === askedFor) {
-        matches = true;
+/**
+ * Evaluate a media query string.
+ * Returns null if the query has nothing to do with color.
+ *
+ * @private
+ * @param {string} mediaQueryString
+ * @returns {boolean|null}
+ */
```
Comment (rugk) [inline src/content_scripts/applyColorSchemeJs.js:87]: This could be a place to keep a reference to the original MDN doc:

```suggestion
  * @see {@link https://developer.mozilla.org/docs/Web/API/Window/matchMedia}
  */
```

**Review by rugk — CHANGES_REQUESTED** [review]
Only some minor code-style things. Otherwise LGTM.

Still need to test practically, but it's a lot more understandable now already.

File: src/content_scripts/applyColorSchemeJs.js (hunk 11 above)
Comment (tartpvule) [reply src/content_scripts/applyColorSchemeJs.js:274]: Hooks are something we created, as opposed listeners that are passed from untrusted code, I'm not as paranoid there.

File: src/content_scripts/applyColorSchemeJs.js (hunk 15 above)
Comment (tartpvule) [reply src/content_scripts/applyColorSchemeJs.js:106]: It is expected to be a listener function, but as it is passed from untrusted code, it can literally be any function and that code is prepared to handle that.
But well, will change it to "listener".

File: src/content_scripts/applyColorSchemeJs.js (hunk 16 above)
Comment (tartpvule) [reply src/content_scripts/applyColorSchemeJs.js:87]: Hard to say, I don't think that link properly describes that function.
I think a link to https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList at the top of the file is more appropriate.

File: src/content_scripts/common.js (hunk 10 above)
Comment (tartpvule) [reply src/content_scripts/common.js:12]: It is used to decide whether to dispatch events in `dispatchChangeEvents()`.
For example, in case NO_OVERWRITE already means "dark" , and the new setting is "dark".

File: src/content_scripts/applyColorSchemeJs.js (hunk 15 above)
Comment (tartpvule) [reply src/content_scripts/applyColorSchemeJs.js]: On another note, the parameters to `addListener` and `removeListener` are named "func" because that is what MDN calls it.

File: src/content_scripts/applyColorSchemeJs.js (hunk 13 above)
Comment (tartpvule) [reply src/content_scripts/applyColorSchemeJs.js]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer

I think object destructuring assignment and shorthand initializer are all implemented well before 67.0a1
But changed it to the older syntax.

File: src/content_scripts/applyColorSchemeJs.js (hunk 16 above)
Comment (rugk) [reply src/content_scripts/applyColorSchemeJs.js:91]: Okay, then feel free to do so.

File: src/content_scripts/applyColorSchemeJs.js (hunk 11 above)
Comment (rugk) [reply src/content_scripts/applyColorSchemeJs.js:290]: Okay, fine. Just saw it in the code, so yeah. :slightly_smiling_face:

File: src/content_scripts/common.js (hunk 10 above)
Comment (rugk) [reply src/content_scripts/common.js:12]: So it is the "original" media query, i.e. the real – not faked one?

If so, just name that variable as such. Though i wonder why you even overwrite it with our value around line 40 here then…

File: src/content_scripts/applyColorSchemeJs.js [hunk 17]
```diff
@@ -4,14 +4,47 @@
...
+let dispatching = false;
+
+/* globals COLOR_STATUS, MEDIA_QUERY_COLOR_SCHEME, MEDIA_QUERY_PREFER_COLOR, fakedColorStatus, getSystemMediaStatus, jsLastColorStatus */
 
 // eslint does not include X-Ray vision functions, see https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/Sharing_objects_with_page_scripts
-/* globals exportFunction, cloneInto */
+/* globals exportFunction */
+
+//
+// See https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList
```
Comment (rugk) [inline src/content_scripts/applyColorSchemeJs.js:46]: That is not JSDoc syntax.

Altghough we don't use CommonJS modules, this site here shows how a header should be formatted that applies to the complete file: https://jsdoc.app/howto-commonjs-modules.html

File: src/content_scripts/applyColorSchemeJs.js [hunk 18]
```diff
@@ -136,15 +368,70 @@ function matchMediaOverwrite(...args) {
...
-    // actually overwrite function
-    exportFunction(matchMediaOverwrite, window, {defineAs: "matchMedia"});
+    overwroteMatchMedia = true;
 }
 
 applyJsOverwrite();
+
+/**
+ * Logs ADDON_FAKED_WARNING if not already did
+ */
```
Comment (rugk) [inline src/content_scripts/applyColorSchemeJs.js:431]: + `@private` 

And AFAIK you also need to set `@returns {void}`. Please have a look at the EsLint errors with our config, they should tell you.

**Review by rugk — APPROVED** [review]
LGTM coding-wise.
So I'll test that out later soon.

Feel free to remind me in a few days if I should forget that. :slightly_smiling_face:

**Comment by tartpvule** [comment]
```
// last setting seen by js
let jsLastColorStatus = null;
```
It's the last thing reported to page's script as written in that comment
It's "real" if in NO_OVERWRITE. fake otherwise

In case of NO_OVERWRITE, the result of `getSystemMediaStatus()` is assigned to it,
otherwise, it's a "faked" value.
This is used when deciding whether to dispatch events or not.

For example:
The "real" theme set by the browser is "dark", so `getSystemMediaStatus()` returns DARK.
When setting is toggled or changed, it could be from NO_OVERWRITE to DARK, or DARK to NO_OVERWRITE.
"change" events should not be dispatched in this case.

**Comment by tartpvule** [comment]
Off topic

While developing this PR, I have an idea to clean up the initialization process of the content scripts, as currently, settings are initialized in 3 places: 1) null at the top of common.js, 2) content script registered from "CssAnalysis.js" (weird name), and 3) `browser.storage.sync.get` in common.js

Would you mind another PR after this one goes through?

**Comment by rugk** [comment]
Oh wow, okay, that is indeed an edge cas,e but awesome and thanks for thinking about it!

If you want, I would change the variable name to `lastSeenJsColorStatus` then.

**Comment by rugk** [comment]
> 1) null at the top of common.js, 2) content script registered from "CssAnalysis.js" (weird name), and 3) browser.storage.sync.get in common.js

We need 1) to avoid race conditions. At least declare and initialize and empty/fallback value, when other settings did not arrive yet. I just fixed such crazy problems in #34.
That's why I'm generally cautious to touch that.

 As for 2) yes `CssAnalysis` injects the new values when they change. i see no other way to do this. AFAIK it had to do with the fact that content scripts cannot listen to the messages triggered by other parts of the add-on (the settings page). So you need to go the way through background scripts.
 BTW it's named like this to differencitate it from the `CSSInject` (or so) JS that actually replaces the CSS stuff, while the analysis part only triggers/analyses the current JS and grabs all stuff to re-inject it.
 
And 3.:
> browser.storage.sync.get in common.js

Uhm IIRC this is also only a workaround to get the settings as fast as possible, as we really race against a white page being shown when it should be black.

So if you want to generalize it, you may take a look (in a new PR please!), but note that most of these things had clear intends in mind and I also did not like to introduce such workarounds instead of using [my simple `AddonSettings` lib](https://github.com/TinyWebEx/AddonSettings). (due to the fact content scripts cannot be injected as ES6 modules, that is a little ugly, I know.)

**Comment by tartpvule** [comment]
On the topic of the initialization process of content scripts.

Believe it or not, that is one of the few places you must use `var` instead of `let`, because of "Temporal Dead Zone" (ES6 spec).
Not using `var` there inevitably leads to race conditions, because the order in which dynamically registered content scripts are run is undefined in relation to static content scripts, but it is guaranteed to be run at document-start.

In this case, things currently go like this:
1. (Maybe run dynamic content script here, and a timer is set for 100ms)
2. (common.js) Initialize with null
3. (common.js) Initialize "modules" (applyColorSchemeJs and applyColorSchemeCss)
4. (Maybe run dynamic content script here - the correct settings apply)
5. The page's code can run here!
5. (common.js) Sometime later, `browser.storage.sync.get` resolves and apply settings again.
6. (Maybe the timer from the dynamic content script expires here)

Race condition! And worse, applyColorSchemeJs and applyColorSchemeCss always see null first.

The correct way to do this is:
- Move all the initialization stuff into a function in "common.js".
- In the dynamic content script, declare (`var`) a variable to store the settings. Detect whether "common.js" is already run, and if so, call the initialization function.
- "common.js" must have an empty declaration (`var`) with no initializer. If that variable is already filled, call the initialization function.
- Don't do `browser.storage.sync.get` at all.

Of course, this is dependent on Firefox's contentScripts API (FF 59), Chromium has nothing like it and no way to solve this race condition at all.

I implemented something like this in a PR I made for another WebExtension (`referer-mod`) -- `https://github.com/airtower-luna/referer-mod/pull/20`

**Comment by rugk** [comment]
So thanks a lot for all this help.

Regarding initialization: yeah, feel free to move that discussion into a new issue, i guess.
From what I see, I guess you can also check whether a `let` or `const` is initialized by [explicitly checking the `typeof` as done here](https://github.com/rugk/website-dark-mode-switcher/pull/34/files#diff-13ac072ebc051aff4cef5db017e908b784d46b1d6e663da70d08d74ecb83bf0cR64), then you get no exceptions on access. So we may still use `let`/`const` don't we?

But if it really cleans up stuff or so, I would be fine with a variable `var initialisationRun =  true` or so, (and exclude that line/var from EsLInt's checks of course), but I'd try to avoid it at best, i.e. let's not do that for every option.

> Don't do browser.storage.sync.get at all.

Yeah, if we can avoid it, the content script likely runs faster, that's fine.

> I implemented something like this in a PR I made for another WebExtension (referer-mod) -- https://github.com/airtower-luna/referer-mod/pull/20

Thanks. I looked at it and it looks quite good. Only serializing all options is a thing I would not do. Besides the fact that this may introduce another performance overhead (serialization and deserialisation likely is not fast), it's just not necessary. I would really only inject the options that need injection.

**Comment by rugk** [comment]
BTW I've also commented on your other PR there to let you know what I would remark for a change (here).
